"""Add Facebook page ID

Revision ID: 215a80f3c760
Revises: aff04158172c
Create Date: 2020-08-20 17:18:49.005284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215a80f3c760'
down_revision = 'aff04158172c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_cred', sa.Column('page_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook_cred', 'page_id')
    # ### end Alembic commands ###
