"""Add subscription tracking

Revision ID: 505ceea824a5
Revises: 215a80f3c760
Create Date: 2020-09-08 15:35:55.980789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505ceea824a5'
down_revision = '215a80f3c760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('expires_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_domain_expires_on'), 'domain', ['expires_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_expires_on'), table_name='domain')
    op.drop_column('domain', 'expires_on')
    # ### end Alembic commands ###
