"""Upgrade model for subscriptions

Revision ID: 8959da1e5b9a
Revises: 505ceea824a5
Create Date: 2020-09-09 23:16:41.949479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8959da1e5b9a'
down_revision = '505ceea824a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('stripe_customer_id', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'domain', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain', type_='unique')
    op.drop_column('domain', 'stripe_customer_id')
    # ### end Alembic commands ###
